// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CharacterCounterController from "./character_counter_controller"
application.register("character-counter", CharacterCounterController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import QuestionGeneratorController from "./question_generator_controller"
application.register("question-generator", QuestionGeneratorController)

import QuestionTypeSwitcherController from "./question_type_switcher_controller"
application.register("question-type-switcher", QuestionTypeSwitcherController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
