name: Ruby on Rails CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - "5433:5432"
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5433/myapp_test"
      DATABASE_HOST: localhost
      DATABASE_PORT: 5433
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Yarn packages
        run: yarn install

      - name: Precompile assets
        run: bundle exec rails assets:precompile

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Start ChromeDriver
        run: |
          chromedriver --version
          chromedriver --port=9515 &

      - name: Set up database schema
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run model tests
        run: bundle exec rspec spec/models

      - name: Run system tests
        run: bundle exec rspec spec/system

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Security audit dependencies
        run: bundle exec bundler-audit --update

      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      - name: Lint Ruby files
        run: bundle exec rubocop --parallel